public class QQNAIConfiguration{
    	public integer intInputCount;
    	public integer intLayerCount;
    	public double dblNeuralNetworkLearningRate;
    	public integer intLayerId;
    	public double dblLayerLearningRate;
    	public double intNeuronCount;
    	public boolean blnLayerIsoutput;
    	public double intBatchSize;
    	public double dblDiscountFactor;
    	public double dblBatchSizeMSEThreshod;
    	public double intpendingBatches;
    	public boolean blnTruncatedDQNActive;
    	
    	public QQNAIConfiguration(){
    		
    	}
}